### ISSUE TITLE
Problem with setting reset

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/WinMBF#34]
There are two problems after setting reset in General section:
* Aspect ratio resets to wider than 4:3
* SFX are not playing.

_(excuse me for being too short, I'll check it more deeper in the evening if necessary)_

**Comment by fabiangreffrath** [comment]
Hm, I cannot seem to reproduce this. Do you have this running with a old `winmbf.cfg` file? Does this happen in window or fullscreen mode? Did SFX play before the menu reset but not after it? Not a single SFX anymore?

**Comment by JNechaevsky** [comment]
Christ, a serious lack of free time. :anguished: More clear explanatory:

* I'm using archive from "winmbf64_FG20191220.zip".
* On fresh install, there is no `winmbf.cfg` file.
* Start the game normally (no need to toggle a full screen mode) and go to Options -> General.
* Reset setting to their defaults: 
  * aspect ratio will be not 4:3 **even after** game restart.
  * not a single sfx will play **until** game restart.

**Comment by fabiangreffrath** [comment]
Ah, that's a pretty old snapshot, actually the first one that even compiled on a 64-bit system. Could you probably send me this corrupted config file? With not 4:3 do you mean that it looks like aspect_ratio_correction was disabled?

**Comment by JNechaevsky** [comment]
> With not 4:3 do you mean that it looks like aspect_ratio_correction was disabled?

Oh, yes. And looks likes it's a `correct_aspect_ratio` right in the end of .cfg file. 
Here's a .cfg file right after action I've described above and exiting normally: [winmbf-cfg.zip](https://github.com/fabiangreffrath/WinMBF/files/4061317/winmbf-cfg.zip)

And by the way, can you please explain just in few words, how can I compile this code under MSYS/Windows? Invoking `./configure.ac` gives following error:
```
# ./configure.ac
./configure.ac: line 4: syntax error next to unexpected marker «[2.69]»
./configure.ac: line 4: `AC_PREREQ([2.69])'
```

**Comment by fabiangreffrath** [comment]
You don't run `configure.ac`. You run `autoreconf -fiv` to generate a `configure` script out of it, which you then run. :wink:

**Comment by JNechaevsky** [comment]
Thanks a lot! Now I know how to do this, and yeah, it's working! 

Interestingly, only these .dll's are needed for me: SDL2.dll, SDL2_mixer.dll and SDL2_net.dll. Probably because they are from SDL website, not MSYS ones (I'm using them for RD).

**Comment by fabiangreffrath** [comment]
Indeed, I can reproduce this issue under Win64, but not under Linux64.

Yes, the EXE really only needs these three libraries. Everything else is dependencies of these respective libraries. And if you add SDL2_Image.dll from somewhere else you will even get PNG screenshots. :grin:

**Comment by fabiangreffrath** [comment]
Could you please check with this EXE (and the same libs as last time) and confirm that the issue is fixed?

[winmbf_x64_git-8bdbefcf.zip](https://github.com/fabiangreffrath/WinMBF/files/4064683/winmbf_x64_git-8bdbefcf.zip)

**Comment by JNechaevsky** [comment]
Gladly, I'm all at your services here! I was using MSYS dlls from `winmbf64_FG20191220.zip` archive, but better I double check with standalone SDL's.

**Comment by fabiangreffrath** [comment]
Should be fixed with *any* set of SDL DLLs.

**Comment by JNechaevsky** [comment]
Can confirm, reset now working perfectly, with both set of DLLs!
