### ISSUE TITLE
improvements for demo_compatibility mode

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/WinMBF#39]
While MBF has an internal `demo_compatibility` mode for playback of Vanilla demos, this is *far* from perfect. I have added all the fixes from the http://prboom.sourceforge.net/mbf-bugs.html website in the https://github.com/fabiangreffrath/WinMBF/tree/demo_fixes branch, but most demos from Choco's `quickcheck` check still desync.

**Comment by fabiangreffrath** [comment]
Anything that I forgot? @fragglet maybe?

**Comment by fragglet** [comment]
The mbf-bugs page was the main thing I was going to suggest, so if you've gone through all those I think you're good.
