### ISSUE TITLE
this needs a name and a README.md and an icon

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/WinMBF#7]
no comment

**Comment by fabiangreffrath** [comment]
And while at it, add myself to the credits screen.

**Comment by fabiangreffrath** [comment]
@JNechaevsky Do you think you could draft an icon for this project? I have a flat icon in mind, a simple solid contour, no colors. Something like these ones (which I cannot use for license reasons):
https://www.flaticon.com/de/packs/woof-woof

How about a dog's head (German shepard, like the one in Wolf3d) with his two eyes in the shape of the Doom logo's `O`s and two horns instead of ears? Or whatever... :wink:

**Comment by JNechaevsky** [comment]
@fabiangreffrath oh yes, I've got your idea. Sure, I think I can handle it, but how urgently is it? Any deadlines?

**Comment by fabiangreffrath** [comment]
Absolutely un-urgent. 😉

**Comment by fabiangreffrath** [comment]
Another idea: A dog's head from the right side with his ear hanging down and the ear's shape is the Doom `D`.

**Comment by JNechaevsky** [comment]
I'm out of home this weekend, and will get slapped if I'll try to do anything related to Doom (yeah-yeah, a private live). But anyways, few ideas about name, we can play around with "MBF" chars.

* FBM - Fiercely Berserker Marine (or something like that)
* BFM (from "BFG") - Best Friend Marine

**Comment by fabiangreffrath** [comment]
I am pretty much settled on "Woof" as a name currently.

**Comment by fabiangreffrath** [comment]
Something like this?

![doomdog](https://user-images.githubusercontent.com/6449237/72252519-b5211c00-35ff-11ea-9961-4c80a15f5949.PNG)

**Comment by JNechaevsky** [comment]
Something like this? Deffinitly need to be more square-shaped instead of rectangle.
Looks likes I'm really sucks with vector graphics...
![oh_gon](https://user-images.githubusercontent.com/21193394/72376761-93b75180-371f-11ea-82ca-05f0ebc25c32.png)

**Comment by fabiangreffrath** [comment]
Pretty good already! :+1:

**Comment by JNechaevsky** [comment]
Phew, here, first draw in Adobe Illustrator in my whole life!
![icon](https://user-images.githubusercontent.com/21193394/72379631-dc253e00-3724-11ea-99fc-2aff8a7fd16d.png)

Does not explains much, but here, as in icon it looks much more interesting:
![image](https://user-images.githubusercontent.com/21193394/72379762-1b538f00-3725-11ea-844d-41cd60ce2d94.png)

Polishing and coloring are still needed, but looks likes we on right track already?

**Comment by fabiangreffrath** [comment]
Cool, I already like it!

**Comment by JNechaevsky** [comment]
Probably "grad v2", but further suggestions about colors are highly appreciated!
![image](https://user-images.githubusercontent.com/21193394/72459993-02a6b000-37dd-11ea-97cb-52549a6367f5.png)

**Comment by fabiangreffrath** [comment]
Phew, not easy, but I think I like the second one the best. The plain white one is still second best.

**Comment by JNechaevsky** [comment]
Take a try, there are both variants in attached archive, in .ico and .png (128x128 and 256x256 formats): 
[icons.zip](https://github.com/fabiangreffrath/WinMBF/files/4066805/icons.zip)

**Comment by fabiangreffrath** [comment]
Awesome, I like them very much! Though I must say, the plain white icon now looks a bit bland compared to the colored one. 

Sorry, but may I request another variant? Instead of a color gradient, I'd like the areas in the colored icon to be filled with the lightest red and brown respectively and have a solid darker outline instead to provide some contrast.

**Comment by JNechaevsky** [comment]
No problem, we will not finish until you say that we are fine.
You mean, both "D" and dog's head should be filled by one type of gradient? From red on top, to brown on bottom, right?

**Comment by fabiangreffrath** [comment]
Wait, no! Solid light red for the "D" with a darker red outline, solid light brown for the dog with a darker brown outline. Sorry for being unclear.

**Comment by JNechaevsky** [comment]
Good evening!

![Solid+Stroke](https://user-images.githubusercontent.com/21193394/72556632-1838da00-38b0-11ea-8541-fd6c1b284442.png) 

![image](https://user-images.githubusercontent.com/21193394/72556683-2d156d80-38b0-11ea-9306-6a83adb069aa.png)

[solid+stroke.zip](https://github.com/fabiangreffrath/WinMBF/files/4073378/solid%2Bstroke.zip)

**Comment by fabiangreffrath** [comment]
Beautiful!

**Comment by JNechaevsky** [comment]
Thanks! Please, take a try and tell if it's good or colors must be modified. Once we will be fine, I'll provide a full source, including Adobe Illustrator file. The only thing - I will be off in this weekend again, private life takes it's time (dang it! where the time when I was sole with tons of free time? always something!)
:two_hearts::blush:

**Comment by fabiangreffrath** [comment]
@JNechaevsky This is going to be the very icon! Could you please do me the favor and export the icons in the exact same format as they are distributed in Chocolate Doom's data directory? And could you please provide the source image in SVG format? That would be great, thanks!

**Comment by JNechaevsky** [comment]
With my pleasure! Here, all the assets, packed same to Chocolate: [icon.zip](https://github.com/fabiangreffrath/WinMBF/files/4089444/icon.zip)
Outside of `data` folder, following source materials are placed:
* icon.ai - source image in vector format (Adobe Illustrator 2020)
* icon.svg - source image in vector format (common)
* icon.psd - raster image which was used for coloring and styling.

I have to be 100% fair. This image was used as a visual template _(not copied over!)_ ([link](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ya-webdesign.com%2Fimages%2Fgerman-shepherd-silhouette-png.png&imgrefurl=https%3A%2F%2Fya-webdesign.com%2Fimage%2Fgerman-shepherd-silhouette-png%2F1007121.html&docid=VnKF6rY4Ks1ObM&tbnid=MqJ2OXc0HPAuXM%3A&vet=10ahUKEwi455_p6YPnAhUK0aYKHZ8BDBcQMwhOKAYwBg..i&w=1600&h=1600&bih=705&biw=1477&q=german%20shepherd%20svg%20icon&ved=0ahUKEwi455_p6YPnAhUK0aYKHZ8BDBcQMwhOKAYwBg&iact=mrc&uact=8)), and this for "D" char ([link](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ya-webdesign.com%2Fimages%2Fdoom-2016-logo-png.png&imgrefurl=https%3A%2F%2Fya-webdesign.com%2Fexplore%2Fdoom-2016-png%2F&docid=f4jD-XfZPa73BM&tbnid=IJc0RhQMlJaVSM%3A&vet=10ahUKEwi7x4bY64PnAhWky6YKHWhmCpMQMwhLKAUwBQ..i&w=2000&h=1035&bih=705&biw=1477&q=doom%20icon%20svg&ved=0ahUKEwi7x4bY64PnAhWky6YKHWhmCpMQMwhLKAUwBQ&iact=mrc&uact=83)).

**Comment by fabiangreffrath** [comment]
@JNechaevsky Any specific license you would like applied to your artwork?

**Comment by JNechaevsky** [comment]
No idea, really. Please consider it as a small gift, which now belongs to you with all related rights. In case of necessity I will make any corrections to the icon, but in the meaning of ownership it's all yours now, so you are free to put it under any licence you wish to. :)

**Comment by fabiangreffrath** [comment]
So, this is OK?
https://creativecommons.org/licenses/by/3.0/

**Comment by JNechaevsky** [comment]
Seems to be perfect. I see there is a newer version 4.0 (https://creativecommons.org/licenses/by/4.0/), which is labeled "international", but looks likes there is nothing changed. Anyways, I'm all for such license.
